### PR TITLE
Switch to improved InMemoryCache from Apollo Client 3

### PR DESCRIPTION
**Pull request by bmulholland**
> As of Apollo Client 3.0, the `InMemoryCache` class is provided by the `@apollo/client` package. No additional libraries are required.

https://www.apollographql.com/docs/react/caching/cache-configuration/

This allows us to drop the dependency on `apollo-cache-inmemory`.

Further, [the new InMemoryCache class provides `typePolicies`](https://www.apollographql.com/docs/react/caching/cache-configuration/), which allows things like converting dates from strings to JS Date objects, so this PR enables:

```
# apolloConfig.js, included via apollo.clientConfigs.default in nuxt.config.js
const inMemoryCacheOptions = {
  typePolicies: {
    Post: {
      fields: {
        createdAt: {
          read(createdAt) {
            return new Date(createdAt)
          },
        },
      },
    },
  },
}
export default (context) => {
  return {
    inMemoryCacheOptions
  }
}
```
(The above is possible already, but requires importing and initializing the new InMemoryCache manually.)

### CODE REVIEW

**Comment by bmulholland** [comment]
I think the tests are failing on master? So it's hard to know if this change is okay, I guess.

**Comment by bmulholland** [comment]
Well, FWIW, I installed it on my project and it's working fine for my limited use case.

**Comment by memic84** [comment]
Will this impact https://github.com/nuxt-community/apollo-module/issues/376?

**Comment by bmulholland** [comment]
@memic84 I have no idea :). Try it out?

**Comment by bmulholland** [comment]
This is totally out of date now.

Not sure what's happening with this project but I don't think anyone is really paying attention.

**Pull request closed without merging**
