### PR TITLE
Add TypeScript Support

### PR DESCRIPTION
**Pull request by kevinmarrec**
After implementing/providing types on official Nuxt and Nuxt-i18n community module, here is a new implementation to provide TypeScript support for the Apollo module.

It provides support for the `$apolloHelpers` object.
I added tests as well ! (`yarn test:types` / `npm run test:types`)

I think we should publish a new LTS `4.0.0-rc2.4` with this feature (it doesn't change the lib, it just provide support for TypeScript), so people will have support without having to use the buggy `4.0.0-rc3` using async components. But I don't know on which branch is the LTS version (with `vue-apollo x.x.x-beta19`)

Additional notes:
I intentionally removed NPM `package-lock.json` file.
It seems that both "linting" with eslint and "fixture tests" with jest throw errors on `master` (a recent PR should fix lint errors, but fixture tests are not passing anyway, probably cause of the SSR `vue-apollo` issue).

### CODE REVIEW

**Comment by dohomi** [comment]
@kevinmarrec sorry for the delay I've been very busy. Can you solve merge conflicts or we try to wait until the SSR bug is resolved..

**Comment by kevinmarrec** [comment]
@dohomi No problem, I'm gonna wait until SSR bug is resolved then I'll update this PR :)

**Comment by robsontenorio** [comment]
@kevinmarrec Now vue 2.6.6 brings necessary SSR support :)

**Comment by kevinmarrec** [comment]
@dohomi Sorry I forgot this PR and unintentionally deleted my fork, I'll reopen a new and updated one. I Will probaly do it in the next 3 days.

**Comment by Torone** [comment]
Where is this documented to use it with typescript? I can not get rid of it and there is nothing explained.

**Comment by kevinmarrec** [comment]
@Torone 

```js
// tsconfig.json

"compilerOptions": {
  "types": [
    "@types/node",
    "@nuxt/vue-app",
    "@nuxtjs/apollo"
  ]
}
```

**Comment by smajl** [comment]
btw, I had to install `vue-apollo` manually and add `vue-apollo` to `compilerOptions/types` as well to remove error on `@Component({ apollo: ... })

**Pull request closed without merging**
