### PR TITLE
Add nuxt configuration types

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
I have add type definition for `NuxtConfiguration`.

This add auto-completion when we write config. Example:
```ts
import NuxtConfiguration from '@nuxt/config'

const config: NuxtConfiguration = {
  apollo: {
    tokenName: 'yourApolloTokenName',
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost:4000'
      }
  }
}
```

Thanks.

### CODE REVIEW

**Comment by kieusonlam** [comment]
Hi @orblazer,

Can you fix all errors on the CircleCI test?

**Comment by orblazer** [comment]
@kieusonlam I dont know how i can fix the types test.
And the error for `dasdsa` its not my.

**Comment by kieusonlam** [comment]
@orblazer 

I found this: https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material/55478377

It might have a couple of way to fix the errors.

The `dasdsa` is just the `console.log` for the `errorHandler` test, so we can leave it there, it doesn't break anything :)

**Comment by orblazer** [comment]
@kieusonlam I have fix the errors but the last need that PR : https://github.com/Akryum/vue-apollo/pull/627

**Comment by kieusonlam** [comment]
Thanks :)

**Pull request merged**
