### PR TITLE
support for multiple clients in Apollo ^2.0.0 (#53)

### PR DESCRIPTION
**Pull request by bjunc**
Similar to PR #37, but for Apollo 2.0.  Using EJS, each client (and respective configs, opts, etc.) are prefixed with the client name.  For instance, if your nuxt config looks like this:

```js
clientConfigs: {
  default: '~/apollo/client-configs/http.js',
  socket: '~/apollo/client-configs/ws.js'
}
```

Then your plugin should look like this:

```js
// *** default Apollo client ***
const defaultCache = defaultClientConfig.cache || new InMemoryCache()
// ...
const defaultFinalOpts = Object.assign({}, defaultOpts, defaultClientConfig, { defaultCache })
// ...
const defaultClient = new ApolloClient(defaultFinalOpts)

// *** socket Apollo client ***
const socketCache = socketClientConfig.cache || new InMemoryCache()
// ...
const socketFinalOpts = Object.assign({}, socketOpts, socketClientConfig, { socketCache })
// ...
const socketClient = new ApolloClient(socketFinalOpts)
```

### CODE REVIEW

**Comment by dohomi** [comment]
@bjunc thanks for your PR. I'm not sure if I understand how a general setup would look like with your changes, could you adjust the examples of the README as well to your pattern or is there no breaking change?
@Akryum @Atinux could you guys review this changes as well, that would be great

**Comment by bjunc** [comment]
@dohomi this is a non-breaking change, and works as the current README suggests (`default` and `test` clients).

In-fact, if you were to try the example currently in the README (`default` and `test` clients) _before_ merging this PR, you'd get the error documented in #53.

That said, it might be worth noting in the "Usage" section that the `default` client is renamed `defaultClient`, but all others are _not_ renamed.  Also, the `default` client is given a shortcut to `apolloProvider.defaultClient`; whereas _all_ clients are accessible via `apolloProvider.clients`.  So for instance:

```js
clientConfigs: {
  default: '~/apollo/client-configs/http.js',
  socket: '~/apollo/client-configs/ws.js',
  test: '~/apollo/client-configs/test.js'
}
```

Would be accessible in a store like this:

```js
export default {
  actions: {
    fooBar (context) {
      let defaultClientShortcut = this.app.apolloProvider.defaultClient
      let defaultClient = this.app.apolloProvider.clients.defaultClient
      let socketClient = this.app.apolloProvider.clients.socket
      let testClient = this.app.apolloProvider.clients.test
    }
}
```

**Comment by dohomi** [comment]
Ok thanks for the clarification, that make sense with the default client. One question though: you are spinning up a seperate client for `ws`, currently we provide an example with subscriptions based on another handling (using split): https://github.com/nuxt-community/apollo-module#example-with-subscription-graphcool-as-example 
Would you prefer to run subscriptions on a seperate client?

**Comment by bjunc** [comment]
That was just an example to demonstrate multiple clients.  I think using [`split`](https://www.apollographql.com/docs/link/composition.html#directional) is intended more as an `if/then/else` use-case (maybe one for SSR, and one for the browser, for instance); but also assumes you'd want to use the rest of link chain (which might be a fair assumption).

I think it's nice to provide the option to use multiple clients, or use Apollo's `split`, as I can't say that I've thought of every use-case and can say definitely that both options don't have their merit.

Side note, we aren't actually using "subscriptions" (pubsub), but we are using sockets for essentially request/response over a persistent connection.  No CORS preflight and persistence make the response times quite fast!

**Pull request merged**
