### PR TITLE
using EJS to generate unique network interface var names (#36)

### PR DESCRIPTION
**Pull request by bjunc**

### CODE REVIEW

**Comment by dohomi** [comment]
for me this looks great. @Atinux do you have any thoughts?

**Comment by dohomi** [comment]
@bjunc can you rebase your PR with the current v3 of this repo? Thanks!

**Comment by bjunc** [comment]
Yeah, no problem.  I'll try to get on that tonight.

**Comment by kedarguy** [comment]
Hey, 

Im using apollo/nuxt 3.0 and got an error trying to add a second client,

Is a plan to keep working on this?

**Comment by bjunc** [comment]
@kedarguy I'll see if I can put the time in tomorrow to reconcile the updates against my PR.  I find myself occasionally needing more than one client as well.

**Comment by pSchaub** [comment]
@bjunc Remember :-) can you fix it?

**Comment by bjunc** [comment]
@pSchaub sorry, I've been really busy with the day job.  I'll do my best to get on this today.

**Comment by pSchaub** [comment]
@bjunc Thanks! My issue is that I really need a fix for #53 - currently multiple clients are not working.

**Comment by bjunc** [comment]
Sorry it took so long to get to this guys, but I just created a PR (#66) that supports multiple clients in Apollo 2.0.  Similar logic to this one.  More info in the PR description.

@dohomi, this PR can be closed as it's not really applicable any more.

**Comment by dohomi** [comment]
Thanks I will close this in favor for #66

**Pull request closed without merging**
