### PR TITLE
initial start to update vue-apollo latest beta .21 

### PR DESCRIPTION
**Pull request by dohomi**
This PR will update to latest changes of vue-apollo

### CODE REVIEW

**Comment by dohomi** [comment]
@Akryum it would be great if you could check if thats how `vue-apollo` should be used. Thanks!

**Comment by negezor** [comment]
There is a problem with fakeInstance, described here
https://github.com/Akryum/vue-apollo/issues/378

**Comment by dohomi** [comment]
@negezor Ok in a separate project I receive the same error: 
```
  TypeError: Cannot read property '$ssrContext' of undefined
  - server-bundle.js:487 Component.options.data
    server-bundle.js:487:14
  - index.js:148 createFakeInstance
    [lumen-cms]/[vue-apollo]/ssr/index.js:14
```
@Akryum is this an internal error of vue-apollo or is the upgraded code not complete yet? Would be great if we find a fix for this.

**Comment by negezor** [comment]
@dohomi Of course, I do not know for sure, but maybe should not try to emulate the very Vue instance?

**Comment by dohomi** [comment]
@negezor I updated to the latest .25 and now everything works fine. Could you update your code and re-validate?

**Comment by negezor** [comment]
@dohomi yes, it works. Thanks 😄

**Comment by dohomi** [comment]
I have to revert - currently I see this error:
```
 ERROR 

  TypeError: Cannot read property 'props' of undefined
  
  - vue.runtime.common.js:1354 normalizeProps
    [lumen-cms]/[vue]/dist/vue.runtime.common.js:1354:23
  
  - vue.runtime.common.js:1456 Object.mergeOptions
    [lumen-cms]/[vue]/dist/vue.runtime.common.js:1456:3
  
  - utils.js:14 exports.getMergedDefinition
    [lumen-cms]/[vue-apollo]/lib/utils.js:14:27
  
  - utils.js:188 Promise.then.component
    [lumen-cms]/[vue-apollo]/ssr/utils.js:188:19
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```
This error is not persistent though, I couldn't figure out why and when it exactly happens. Usually after few reloads its gone

**Comment by dohomi** [comment]
@Akryum the error is being shown after the change of https://github.com/nuxt-community/apollo-module/pull/158/commits/5ad31177dacc8ca243db9677d62fc48ff0214186
this happens in beta.25

**Comment by AndrewBogdanovTSS** [comment]
any updates regarding this issue?

**Comment by dohomi** [comment]
@Akryum @Atinux do you guys have any idea how to solve this for this module? Currently the upgrades are not possible due to the SSR problem

**Comment by jakub300** [comment]
Hey, I was able to debug this and filled Akryum/vue-apollo#402.

Also keep in mind that that new SSR is throwing errors for many apps (see Akryum/vue-apollo#392).

Last thing, in the last line modified in this PR it should be `nuxtState.apollo = ApolloSSR.getStates(apolloProvider)` instead of `nuxtState.apollo = ApolloSSR.exportStates(apolloProvider)`. With that change this PR will work with simple projects (that doesn't touch any of the above issues).

**Comment by aldarund** [comment]
A side note
>nuxtState.apollo = ApolloSSR.exportStates(apolloProvider)
Nuxt state should be serializable. So there should be only values, not a functions or Symbols. So it need to make sure that there no not serializeable data like Symbols

**Pull request merged**
