### PR TITLE
Revert vue-apollo to beta-13

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
https://github.com/Akryum/vue-apollo/issues/333

### CODE REVIEW

**Comment by stevefan1999** [comment]
Well, or maybe we could make a step back: Use peerDependencies instead. This however requires everyone to manually install their own vue-apollo on demand.

**Comment by stevefan1999** [comment]
🤔Fixing vue-apollo version on package.json kinda works...
```
"vue-apollo": "3.0.0-beta.13",
```
But I see two distinct vue-apollo packages here...
```
"@nuxtjs/apollo@^4.0.0-rc1":
  version "4.0.0-rc1"
  resolved "https://registry.yarnpkg.com/@nuxtjs/apollo/-/apollo-4.0.0-rc1.tgz#2dc9470d5c23df43c176421372bc5d8699425d37"
  dependencies:
    cookie "^0.3.1"
    isomorphic-fetch "^2.2.1"
    js-cookie "^2.2.0"
    vue-apollo "^3.0.0-beta.19"
    vue-cli-plugin-apollo "^0.16.0"
...
vue-apollo@3.0.0-beta.13:
  version "3.0.0-beta.13"
  resolved "https://registry.yarnpkg.com/vue-apollo/-/vue-apollo-3.0.0-beta.13.tgz#fc934b3abb44cb74f4789c5a6713c0df69192988"
  dependencies:
    throttle-debounce "^1.0.1"

vue-apollo@^3.0.0-beta.19:
  version "3.0.0-beta.19"
  resolved "https://registry.yarnpkg.com/vue-apollo/-/vue-apollo-3.0.0-beta.19.tgz#26f5dbb6bd2a2a7f567320d293442d3c7ae70a08"
  dependencies:
    throttle-debounce "^2.0.0"
```

**Comment by dohomi** [comment]
@stevefan1999 the downgrade does not affect all users so I rather not merge your PR. I'm pretty sure @Akryum will have a fix in place very soon and then we can rather upgrade the dependency to the new bugfix version

**Comment by dohomi** [comment]
closed in favor for vue-apollo beta.25

**Pull request closed without merging**
