### PR TITLE
add browserHttpEndpoint option for client requests close #272

### LINKED ISSUE #272: Option for separate endpoints for server and client
### What problem does this feature solve?

When running locally, the Apollo client on the server and in the browser can both use `http://localhost:8000/graphql` (or whatever the port is) as the `httpEndpoint` and everything works fine:

``` js
export default {
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: `http://${HOST}:${PORT}/graphql`,
      },
    },
  },
}
```

However, when deployed to production (or any other non-local environment), the server can use `http://localhost:8000/graphql`, but the browser definitely cannot. The simplest solution in my case is for the client value to be just `/graphql`, and the browser will assume the same domain and port as the currently-running page.

Both [`@nuxtjs/axios`][@nuxtjs/axios] and [`@nuxt/http`][@nuxt/http] have separate options for the server (`baseURL`) and the browser (`browserBaseURL`). It seems the Apollo module needs the same to support anyone writing an app where their UI and API are running on the same server. (Unless I missed something. Apollo seems to assume that the API is running on a different server.)

[@nuxtjs/axios]: https://axios.nuxtjs.org/options
[@nuxt/http]: https://http.nuxtjs.org/api/

I tried the following workaround in `nuxt.config.js` of using multiple Apollo clients, but I wasn't able to get it working:

``` js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: "localhost:8000/graphql",
      },
      browser: {
        httpEndpoint: "/graphql",
      },
    },
  },
};
```

I tried putting the following in every Vue component to dynamically select the right client based on the environment, but got errors in the browser:

``` html
<script>
  export default {
    apollo: {
      $client: typeof window === "undefined" ? "default" : "browser",
      // ...
    },
  };
</script>
```

### What does the proposed changes look like?

In `nuxt.config.js`, just like for the [`@nuxtjs/axios`][@nuxtjs/axios] and [`@nuxt/http`][@nuxt/http] modules, the Apollo module should support separate endpoint values for server and client:

``` js
export default {
  modules: [
    "@nuxtjs/apollo",
  ],
  apollo: {
    clientConfigs: {
      default: {
        httpEndpoint: "localhost:8000/graphql",
        browserHttpEndpoint: "/graphql",
      },
    },
  },
};
```

[@nuxtjs/axios]: https://axios.nuxtjs.org/options
[@nuxt/http]: https://http.nuxtjs.org/api/

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c252">#c252</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by kieusonlam**
Defines the http endpoint which is used and prepended to make client side requests.

Related: #272

### CODE REVIEW

**Comment by kieusonlam** [comment]
I released new version.

**Comment by chriscalo** [comment]
Thanks, working great for me 🙏

**Comment by rchl** [comment]
Looks like this wasn't documented.

**Comment by chriscalo** [comment]
Docs update proposed in #277. Feel free to use or discard in favor of something better.

**Pull request merged**
