### PR TITLE
feat!: Support Nuxt 3

### LINKED ISSUE #297: websocketsOnly not always
### What problem does this feature solve?

ApolloClient use httpEndpoint before the websocket is not connected.

### What does the proposed changes look like?

Please create a force mode for websocketsOnly, thar waits for websocket connection before quering.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c277">#c277</a>)</em></sub></div>

### LINKED ISSUE #312: Cookies not sent in SSR mode
### Version

[v4.0.0-rc.19](https://github.com/apollo-module/releases/tag/v4.0.0-rc.19)

### Reproduction link

[https://pyj86.sse.codesandbox.io](https://pyj86.sse.codesandbox.io)

### Steps to reproduce

If `httpLinkOptions.credentials = true` it seems the `Cookie` header is set when client side, but not when the SSR request is happening.

Setup `nuxt.config.js` like so:
```
    apollo: {
        authenticationType: "Basic",
        clientConfigs: {
            default: "~/plugins/apollo-config-default.js"
        }
    }
```

And then in `apollo-config-default.js`

```
export default function() {
    return {
        httpEndpoint: process.env.DEFAULT_ENDPOINT,
        getAuth: () => process.env.BASIC_API_TOKEN || "",
        httpLinkOptions: {
            credentials: "include"
        }
    }
}
```

Hard load to a public URL, like: https://pyj86.sse.codesandbox.io/

It works fine, browse to a private URL via a nuxt-link and it works fine.

Hard load into a private URL and it will give SSR node not matching server-rendered errors.

This page will only work if you are logged into backend. DM me for the logins which is here: https://stackhaus-backend.funkhaus.us /wp-admin

Public page: https://pyj86.sse.codesandbox.io/
Private page: https://pyj86.sse.codesandbox.io/featured/private-page

### What is expected ?

Cookie header should be sent when both client side and SSR

### What is actually happening?

SSR gives node not matching server-rendered errors

### Additional comments?

I'm running WordPress as a headless CMS and trying to get preview/draft/private pages/posts working. The setup results in the backend having a different domain to your frontend, like `example.com` and `api.example.com`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c296">#c296</a>)</em></sub></div>

### LINKED ISSUE #407: apollo client v3
When updated nuxt apollo module ?

### LINKED ISSUE #413: Nuxt 3
Will there be an update when nuxt 3 comes out?

### LINKED ISSUE #426: Authorization header with wsEndpoint not working even if refresh the page !!
Screenshot_6

### LINKED ISSUE #431: Is it possible to update vue-apollo to the latest version
The latest version of vue-apollo is 3.1.0, but the version of package.json is 3.0.5.

I think vue-apollo had fixed some problems, is it possible [apollo-module](https://github.com/nuxt-community/apollo-module) will update to the latest verison?

### PR DESCRIPTION
**Pull request by Diizzayy**
This PR introduces a variety of changes, many of which are in-fact _breaking changes._

The first and perhaps biggest being the adaptation of Vue 3 using [Vue Apollo v4](https://v4.apollo.vuejs.org)

## Changes

- `clientConfigs` is now `clients`
- `authenticationType` is now `authType`
- `tokenName` defaults to `apollo:<client-name>.token`
- `proxyCookies` flag
- `authHeader` support
- `tokenStorage` - ( cookie or localStorage )
- `defineApolloClient` helper
- auto imports gql wrapper and apollo composables
- new `apollo:auth` hook; replaces `getAuth`
- new `apollo:error` hook; replaces global `errorHandler`
- Improved auth integration via cookie and localStorage
- Migrated from `subscriptions-transport-ws` to `GraphQLWsLink` via [graphql-ws](https://www.npmjs.com/package/graphql-ws)
- Improved loading of `.gql` / `.graphql` files (Vite & Webpack)
- Improved SSR support
- Proper documentation site
- HMR for external client config files ( Greatly improves DX )
- support for [Vue Apollo Composables](https://github.com/vuejs/apollo/tree/v4/packages/vue-apollo-composable) ie: `useQuery`, `useMutation`, `useSubscription`, etc...

<hr>

Closes #312
Closes #297
Closes #426

### CODE REVIEW

**Review by kieusonlam — APPROVED** [review]

**Review by sahanatroam — APPROVED** [review]

**Comment by atinux** [comment]
I reviewed the docs and looks good to me now.

Beautiful work ❤️

**Comment by slavanossar** [comment]
Had some time to play around with this and test it out on a demo project, working really nicely. I'm not sure how useful I'll be, but if you need any help with testing or anything else let me know.

Thanks @Diizzayy and anyone else who has contributed, amazing work in putting this together!

**Comment by joshistoast** [comment]
> Had some time to play around with this and test it out on a demo project, working really nicely. I'm not sure how useful I'll be, but if you need any help with testing or anything else let me know.
> 
> Thanks @Diizzayy and anyone else who has contributed, amazing work in putting this together!

Would love to play with this but having difficulties with `upstream dependency conflicts`, how'd you install it? Would also love to know what's hindering this from being merged.

**Comment by slavanossar** [comment]
> > Had some time to play around with this and test it out on a demo project, working really nicely. I'm not sure how useful I'll be, but if you need any help with testing or anything else let me know.
> > Thanks @Diizzayy and anyone else who has contributed, amazing work in putting this together!
> 
> Would love to play with this but having difficulties with `upstream dependency conflicts`, how'd you install it? Would also love to know what's hindering this from being merged.

I was also having issues so my installation is semi-manual, I'm only using it for testing at the moment so it's not critical to have it working seamlessly just yet:

1. Add branch as dependency
```bash
yarn add Diizzayy/apollo-module#chore/nuxt3
```

2. Separately clone branch, install packages and build `/dist`
```bash
pnpm install && pnpm build
```
> The build step would fail for me when doing it from `node_modules/@nuxtjs/apollo` within repository

3. Copy `/dist` files to something like `lib/apollo-module` in repository
4. Specify `postinstall` script in `package.json`
```json
{
  "scripts": {
    "postinstall": "cp -R lib/apollo-module node_modules/@nuxtjs/apollo/dist"
  }
}
```

Obviously this requires completing steps 2 & 3 again as updates are pushed to the branch.

**Comment by dwin0** [comment]
@Diizzayy Thanks for putting in the effort to make it compatible with Nuxt 3!
@kieusonlam, when will this change be merged into v5 and when do you plan to make v5 official?

**Comment by Diizzayy** [comment]
@dwin94 This will be merged and released under v5 soon enough.

**Comment by Luferov** [comment]
waiting for a stable release of nuxt?

**Pull request merged**
